### ISSUE TITLE
Error: Webhook URL must be defined to create subscriptions

### ISSUE THREAD

**Issue by shajanjp** [super-ienien/twitter-webhooks#1]
I am getting this error when running the sample code
Error: Webhook URL must be defined to create subscriptions
![screenshot from 2018-08-22 19-07-30](https://user-images.githubusercontent.com/2943609/44466748-b33b6f00-a63e-11e8-96f9-e231522fba77.png)

**Comment by shajanjp** [comment]
Thanks,  my webook endpoint was not properly configured.

**Comment by vino-vinoth** [comment]
> Thanks, my webook endpoint was not properly configured.

did you resolve it.i've got same issue..

**Comment by super-ienien** [comment]
Hi, could you show me your code please ?

**Comment by vino-vinoth** [comment]
const userActivityWebhook = twitterWebhooks.userActivity({
    serverUrl: 'https://b216d341.ngrok.io',//i'm local ngork for testing
    route: '/',
    consumerKey: '******',
    consumerSecret: '*******',
    accessToken: '*******',
    accessTokenSecret: '***',
    environment: '**', //default : 'env-beta'
    app
});

//Register your webhook url - just needed once per URL
userActivityWebhook.register();

//Subscribe for a particular user activity
userActivityWebhook.subscribe({
        userId: 'my user id',
        accessToken: 'my access token',
        accessTokenSecret: 'my access token secret'
    })
const server = https.createServer({
    app
});


server.listen(6000);

**Comment by super-ienien** [comment]
Tour serverUrl should be accessible to the world. The error message « Webhook
URL must be defined to create subscriptions »
mean that Twitter cannot reach your server.

You should get a valid response from this url :
https://b216d341.ngrok.io/?crc_token=123456

**Comment by vino-vinoth** [comment]
> Tour serverUrl should be accessible to the world. The error message « Webhook URL must be defined to create subscriptions » mean that Twitter cannot reach your server. You should get a valid response from this url : https://b216d341.ngrok.io/?crc_token=123456

![Screenshot from 2019-07-03 15-47-58](https://user-images.githubusercontent.com/25799343/60584136-0e370a00-9daa-11e9-8aff-19e596fc0270.png)
actually i got this when test..

**Comment by super-ienien** [comment]
You have to route your server’s port 443 to your node app, not to an Apache server

**Comment by vino-vinoth** [comment]
thanks.
can i use the ngork for serverURL?
and  i have used the server port 443 as result is :Error: listen EACCES: permission denied 0.0.0.0:443

**Comment by super-ienien** [comment]
Yes you can use ngork but you have to shut down your Apache server

**Comment by vino-vinoth** [comment]
i am new to this, could you please tell me how to get ServerUrl??

**Comment by killallskywalker** [comment]
Hi , im not sure why im get  

>  Error: Webhook URL must be defined to create subscriptions.

even my url is working . 

![Screenshot 2020-05-14 at 3 58 41 PM (2)](https://user-images.githubusercontent.com/19742186/81908457-d4ef3d80-95fb-11ea-8a4c-c35401a0aad4.png)
