### ISSUE TITLE
Can't register my webhook url

### ISSUE THREAD

**Issue by mapage1714** [super-ienien/twitter-webhooks#11]

**Comment by mapage1714** [comment]
Hi, I'm having an issue while registering my webhook url. Those are my settings:

const userActivityWebhook = twitterWebhooks.userActivity({
	serverUrl: 'https://twitter--server.herokuapp.com',
	route: '/webhooks/twitter',
	consumerKey: process.env.CONSUMER_KEY,
	consumerSecret: process.env.CONSUMER_SECRET,
	accessToken: process.env.ACCESS_TOKEN_KEY,
	accessTokenSecret: process.env.ACCESS_TOKEN_SECRET,
	environment: 'dev', //default : 'env-beta'
	app,
});

I have the server on heroku, the tokens and keys are ok, I double-check. And the server is up and running fine. Maybe I'm missing something?

Thanks in advance

**Comment by super-ienien** [comment]
Hi,

Your url is not reachable : 
https://twitter--server.herokuapp.com/webhooks/twitter?crc_token=test

Do you have other routes configured on your express app ?

**Comment by mapage1714** [comment]
Hi, 

I had an issue with my server. Everything is fixed now. Thank you anyway for your time.
