### ISSUE TITLE
Error: Application cannot perform write actions

### ISSUE THREAD

**Issue by imomin** [super-ienien/twitter-webhooks#2]
I just installed your npm and testing the twitter webhook.
I followed your instruction from read me page. When I run the app, I get an error (see below screenshot).
I have my app permission set to "Read-only".
Any idea why I'm getting the error?

**Comment by super-ienien** [comment]
Hello, 

You need to edit your app’s permissions and set them to read and write and direct messages.

**Comment by imomin** [comment]
But, my app doesn't need write and DM permission. Just to move forward I went ahead and updated the permission.
Now, I am getting following error. I got client the accessToken and accessTokenSecret from oAuth (after updating the R/W DM permission). 
Any idea?

![image](https://user-images.githubusercontent.com/1074352/45255598-356da800-b34e-11e8-8f31-a352fa69d84c.png)

**Comment by super-ienien** [comment]
First, yes it’s not obvious but your app need read and right permissions in order to use account activity API. So your app needs it.

Two, you get this error because you changed your app permissions but the user’s token you are using was issued when your app was in read only. You need to revoke the app from your twitter account in your twitter settings. And then you need to get new tokens by sign in again to your app with your account.

**Comment by super-ienien** [comment]
When do you get the error forbidden ? What request do you make ?

**Comment by imomin** [comment]
When following code is executed.
 
```
 userActivityWebhook.subscribe({
    userId: '###########',
    accessToken: '#########-$$$$$$$$$$$$$$$$$$$$$$$$$$$$,
    accessTokenSecret: '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
}).then(function (userActivity) {
    userActivity
    .on('favorite', (data) => console.log (userActivity.id + ' - favorite'))
    .on ('tweet_create', (data) => console.log (userActivity.id + ' - tweet_create'))
    .on ('follow', (data) => console.log (userActivity.id + ' - follow'))
    .on ('mute', (data) => console.log (userActivity.id + ' - mute'))
    .on ('revoke', (data) => console.log (userActivity.id + ' - revoke'))
    .on ('direct_message', (data) => console.log (userActivity.id + ' - direct_message'))
    .on ('direct_message_indicate_typing', (data) => console.log (userActivity.id + ' - direct_message_indicate_typing'))
    .on ('direct_message_mark_read', (data) => console.log (userActivity.id + ' - direct_message_mark_read'))
    .on ('tweet_delete', (data) => console.log (userActivity.id + ' - tweet_delete'))
}).catch(err => {
  console.log('err');
  console.log(err);
});
```

**Comment by super-ienien** [comment]
Did you register your webhook with the register method ? Errors returned by twitter’s API are well documented in the API.

I can help to analyze the errors but I need you to paste the complete error here.

**Comment by super-ienien** [comment]
Could you add a catch on the register function and log the error ?

**Comment by imomin** [comment]
Same error
register
{ Error: Forbidden.
    at Request.request [as _callback] (/Users/imtiyaz/Documents/projects/SocialProofApp/node_modules/twitter-webhooks/lib/helpers.js:16:33)
    at Request.self.callback (/Users/imtiyaz/Documents/projects/SocialProofApp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/Users/imtiyaz/Documents/projects/SocialProofApp/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/Users/imtiyaz/Documents/projects/SocialProofApp/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19) code: 200, statusCode: 403, body: { errors: [ [Object] ] } }

**Comment by super-ienien** [comment]
I think you are getting this error because you webhook is already registered and you are executing the register method each time you start your server. But you can’t register a webhook twice.

**Comment by imomin** [comment]
OK, let me try to take off the register code.

**Comment by imomin** [comment]
Took it off but same error. Do you think it has already "subscribe" for the given accessToken?

**Comment by super-ienien** [comment]
In order to understand what is going on you need to get the full error. When twitter sends a 403 error it also send a json payload containing another error message that explain why you are receiving the error. 

Make a console.error(error.body) in your catch to see the details.

**Comment by imomin** [comment]
console.log(err.body); give me following { errors: [ { code: 200, message: 'Forbidden.' } ] }

console.log(JSON.stringify(err)); give me following 
{"code":200,"statusCode":403,"body":{"errors":[{"code":200,"message":"Forbidden."}]}}

**Comment by super-ienien** [comment]
Sorry, I think I need to update the module to have the full error. I will be able to do that in several hours.

**Comment by super-ienien** [comment]
In the mean time you could test that your CRC is working

**Comment by super-ienien** [comment]
Ok so, in fact the answer is in the error : twitter is sending a 403 Forbidden http response with an error code 200.

The API documentation doesn't contain any explanation for this error... But in the twitter's dev forum you can find this : [https://twittercommunity.com/t/forbidden-response-from-creating-new-webhook-endpoint/105662](https://twittercommunity.com/t/forbidden-response-from-creating-new-webhook-endpoint/105662)

I think you need an environment, that's a new thing twitter invented in order to manage their paying APIs. You should create one following this documentation : [https://developer.twitter.com/en/docs/basics/developer-portal/guides/dev-environments.html](https://developer.twitter.com/en/docs/basics/developer-portal/guides/dev-environments.html)

**Comment by imomin** [comment]
OK, I figured it out. DO NOT use "env-beta" in your API URL.
 https://api.twitter.com/1.1/account_activity/all/env-beta/webhooks.json

Substitute "env-beta" with the name of the "Dev environment label" from https://developer.twitter.com/en/account/environments. 

Now I can see actual error, that is, "'{"errors":[{"code":214,"message":"Webhook URL does not meet the requirements. Port other than 443 is not allowed."}]}'"

**Comment by super-ienien** [comment]
Yes that’s a setting you can set when you create the userActivity middleware. This is the ˋenvironment setting`

Now you’re getting this error because your server is not using https

**Comment by imomin** [comment]
Yep, that did it. I'm using https but on a different port. Just how my network behind the router is setup.
I am going to close this issue since it's not relevant to your module.

**Comment by super-ienien** [comment]
Ok, feel free to open a new issue if you are encountering troubles using this module ;)
