### ISSUE TITLE
How to send direct message?

### ISSUE THREAD

**Issue by cansado2930** [super-ienien/twitter-webhooks#4]
Hi,
I have installed this sdk and I have got to read direct messages, but I don't understand how I should use it to answer them. Could you tell me some tip?
Thank you

**Comment by super-ienien** [comment]
Hi !

this module doesn't provide a way to send request to twitter's api. You should use some other module like twit or twitter-lite.

Cheers

**Comment by cansado2930** [comment]
Thank you!

**Comment by iFlameing** [comment]
@cansado2930 I am also trying this library but I didn't get any response when someone message me. You can see the code at https://github.com/iFlameing/my-twitter-bot. Please help did you setup the webhook url at developer account?

**Comment by cansado2930** [comment]
@iFlameing I have seen your code, i have comparated with my server and it seems that it is good. So I recommend you in order to debug it, use ngrok on your computer and use VS community o VS Code and put breakpoint on the different points in order to see if there are some problem.
